name: JamieTiernay
favicon: null
layout_spectrum: 0.5820060325786471
typography_spectrum: 0.0021317226346582174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9188020899891853
  lightness: 0.10004948801361024
  saturation: 0.22536200867034495
  rhythmicContrast: 0.9773806945886463
purpose: []
