name: JamieTiernay
favicon: null
layout_spectrum: 0
typography_spectrum: 0.0021317226346582174
title: Jamie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#695850'
    - '#74deda'
    - '#fed772'
    - '#9e7150'
    - '#cf905b'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
